module/src/components/button/button.prototyping.scss, module/src/components/confirmButton/confirmButton.component.tsx, module/src/components/confirmButton/confirmButton.stories.tsx, module/src/components/confirmButton/index.ts, module/src/components/dialog/dialog.basic.scss, module/src/components/dialog/dialog.hooks.tsx, module/src/components/modal/modal.hooks.tsx, module/src/components/tag/tag.prototyping.scss, module/src/index.ts, module/src/theme/mixins.scss
- Added a ConfirmButton which shows a confirmation dialog before running its given onclick event
ARM-99
=> Feature/arm 99/dialog button

module/src/hooks/calendar/calendar.hooks.ts, module/src/hooks/calendar/calendar.utils.ts, playground/src/views/examples/calendar.tsx
Fixed calendar input to not select today if selection is undefined, also month skippers navigate through years.
- [Y] are your changes in Storybook?
- [Y] are any breaking changes documented in `docs/migrating_from_oldstrong.md`?
- [Y] does _everything_ have jsdoc?
- [Y] is everything exported from index.ts?
=> fix: Minor fixes to calendar input

module/src/components/confirmPasswordInput/index.ts, module/src/components/index.ts
=> fix: export confirm password input

module/src/components/stepper/stepper.basic.scss
- Added a missing $ parameter to a variable which was breaking compilation /minification
=> fix: fix missing $ on variable causing compilation issues

module/src/components/checkboxInput/checkboxInput.component.tsx
=> fix: ARM-48 changed default state from false to the current checked value

module/src/hooks/form/form.hooks.ts, module/src/hooks/form/form.stories.mdx, module/src/hooks/form/form.types.ts, module/src/hooks/form/form.utils.ts, playground/src/servers/memory.ts, playground/src/views/user/user.tsx
Initial state can also be passed as a React callback. The callback will be executed:
1. Once initially with no parameters passed to it, it will be expected to return the initial state for the form binder.
2. Again each time it's dependencies update, in this case it will receive the current form state as a param and be expected to return updated form state.
This is extremely useful when a form relies on remote data that could update at any time, it allows the form to update with the latest changes from the server without losing the user's current edits by completely replacing the form data with the remote update.
**NOTE:** When using an initial data function, be aware that it will be executed to provide initial data whenever it's reference updates. It's essential therefore that any initial …
=> feat: a form's initial data can now be supplied as a dynamic callback

module/src/hooks/form/form.state.ts
- Fixed a bug preventing the root validation clear method from working
=> fix: fixed a bug preventing the root validation clear method from working

module/src/components/modal/modal.hooks.tsx
- Added missing dependencies to modal callback.
- Fixes issue https://github.com/Rocketmakers/armstrong-edge/issues/40
=> fix: ARM-40 added missing dependencies to modal callback

module/src/components/select/select.component.tsx
- Fix console errors caused by a default value on the select element when a placeholder is present, if there's also an initial value present
[ARM-180](https://rocketmakers.atlassian.net/browse/ARM-180)
=> Feature/arm 180/select console warnings

module/src/components/dropdown/dropdown.component.tsx, module/src/components/dropdownItems/dropdownItems.component.tsx, module/src/components/index.ts, module/src/components/modal/modal.component.tsx, module/src/components/tail/index.ts, module/src/components/tail/tail.basic.scss, module/src/components/tail/tail.component.tsx, module/src/components/tail/tail.stories.tsx, module/src/components/tooltip/tooltip.basic.scss, module/src/components/tooltip/tooltip.component.tsx, module/src/components/tooltip/tooltip.prototyping.scss, module/src/components/tooltip/tooltip.stories.tsx, module/src/hooks/form/form.hooks.ts, module/src/theme/mixins.scss, module/src/theme/mixins.stories.mdx, module/src/theme/variables.stories.mdx, module/src/utils/directions.ts
proposed in the [Pure Salvage Proposal](https://docs.google.com/document/d/11En_it9fnxWJI_PL5RhS5MzxhFKjX93iYpMtmIu0AP0/edit)
- Add new Tail component
- Add an option to centre the Tooltip on mobile in CSS
- Add an option to remove the Tail on the Tooltip
- Add an option to open the Tooltip on children click
ARM-XX
=> Feature/centre tooltip (optionally on mobile)

module/src/components/dropdown/dropdown.basic.scss
- fix dropdown responsiveness
ARM-XX
=> fix: ensure dropdown modal has correct specificity on mobile

module/src/components/calendarDisplay/calendarDisplay.component.tsx, module/src/components/calendarInput/calendarInput.component.tsx, module/src/components/dialog/dialog.component.tsx, module/src/components/dialog/dialog.hooks.tsx, module/src/components/listBox/listBox.component.tsx, module/src/components/listBoxMulti/listBoxMulti.component.tsx, module/src/components/passwordInput/passwordInput.component.tsx, module/src/components/rating/rating.component.tsx, module/src/components/select/select.component.tsx, module/src/components/tag/tag.component.tsx, module/src/components/tagInput/tagInput.component.tsx, module/src/components/toast/toast.component.tsx
-  Button type=button added to internal buttons to prevent form submit
ARM-XX
=> Internal button type fix

module/src/components/switchInput/switchInput.component.tsx
- Made the switch component keyboard accessible (supports space/enter/left/right)
=> Fix: Accessible switch

.github/workflows/test.yml, module/package-lock.json, module/package.json
=> fix: ARM-256 fixes test pipeline to use IP rather than localhost

module-new/src/components/toast/toast.component.tsx, module-new/src/components/toast/toast.context.tsx, module-new/src/components/toast/toast.stories.tsx
- Tests for toast in module-new
ARM-318
=> chore: ARM-318 - Tests for toast in module-new

module-new/src/components/dialog/dialog.component.tsx, module-new/src/components/dialog/dialog.stories.tsx, module-new/src/components/input/input.component.tsx
- Added tests to dialog component in module-new
ARM-282
=> chore: ARM-282 - Added tests to dialog component in module-new

module-new/src/components/autoResizer/autoResizer.component.tsx, module-new/src/components/autoResizer/autoResizer.stories.tsx, module-new/src/components/autoResizer/autoResizer.theme.css, module-new/src/components/autoResizer/index.ts, module-new/src/hooks/form/form.hooks.ts, module-new/src/hooks/useBoundingClientRect.spec.ts, module-new/src/hooks/useBoundingClientRect.ts, module-new/src/hooks/useCompareValues.spec.ts, module-new/src/hooks/useContentMemo.spec.ts, module-new/src/hooks/useContentMemo.ts, module-new/src/hooks/useDidUpdateEffect.spec.ts, module-new/src/hooks/useEventListener.spec.ts, module-new/src/hooks/useEventListener.ts, module-new/src/hooks/usePreviousValue.spec.ts, module-new/src/hooks/useResizeObserver.spec.ts, module-new/src/hooks/useResizeObserver.ts, module-new/src/utils/arrays.ts, module-new/src/utils/objects.ts
- Added AutoResizer component and all relevant hooks
- Added unit tests for all hooks
- Implemented `useContentMemo` where appropriate.
ARM-273
=> Feature/auto resizer - module new

module-new/src/components/dateTimeInput/dateTimeInput.component.tsx, module-new/src/components/dateTimeInput/dateTimeInput.stories.mdx, module-new/src/components/dateTimeInput/dateTimeInput.stories.tsx, module-new/src/components/dateTimeInput/dateTimeInput.theme.css, module-new/src/components/dateTimeInput/index.ts, module-new/src/components/input/input.component.tsx, module-new/src/components/input/input.theme.css
- Added an input for date and time together
ARM-281
=> feat: ARM-281 - Date and time input

module-new/src/components/characterLimit/characterLimit.component.tsx, module-new/src/components/characterLimit/characterLimit.stories.tsx, module-new/src/components/characterLimit/characterLimit.theme.css, module-new/src/components/characterLimit/index.ts, module-new/src/index.ts
- Added character limit component
ARM-277
=> feat: ARM-277 - Added character limit component

module-new/src/components/button/button.component.tsx, module-new/src/components/checkbox/checkbox.component.tsx, module-new/src/components/checkbox/checkbox.stories.tsx, module-new/src/components/checkbox/checkbox.theme.css, module-new/src/components/checkboxList/checkboxList.component.tsx, module-new/src/components/checkboxList/checkboxList.stories.tsx, module-new/src/components/checkboxList/checkboxList.theme.css, module-new/src/components/checkboxList/index.ts, module-new/src/components/codeInput/codeInput.component.tsx, module-new/src/components/config/config.context.tsx, module-new/src/components/input/input.component.tsx, module-new/src/components/radioGroup/radioGroup.stories.tsx, module-new/src/components/radioGroup/radioGroup.theme.css, module-new/src/components/reactSelect/singleSelect/singleSelect.component.tsx, module-new/src/components/textArea/textArea.component.tsx, module-new/src/index.ts, module-new/src/types/core.ts, module-new/src/types/options.ts
- Implemented the checkbox list component.
- Fix the inconsistent props with radio list & checkbox single.
- Abstracted display size to a central type.
ARM-279
=> feat: ARM-279 - Checkbox List

module-new/package-lock.json, module-new/package.json, module-new/src/components/config/config.context.tsx, module-new/src/components/tooltip/index.ts, module-new/src/components/tooltip/tooltip.component.tsx, module-new/src/components/tooltip/tooltip.stories.tsx, module-new/src/components/tooltip/tooltip.theme.css, module-new/src/index.ts
- Added radix tooltip component to module-new
ARM-319
=> feat: ARM-319 - Added radix tooltip component to module-new

module-new/package-lock.json, module-new/package.json, module-new/src/components/progressBar/index.ts, module-new/src/components/progressBar/progressBar.component.tsx, module-new/src/components/progressBar/progressBar.stories.tsx, module-new/src/components/progressBar/progressBar.theme.css, module-new/src/index.ts
- Added progress bar component to module-new
ARM-299
=> feat: ARM-299 - Added progress bar component to module-new

module-new/package-lock.json, module-new/package.json, module-new/src/components/checkbox/checkbox.component.tsx, module-new/src/components/rangeInput/index.ts, module-new/src/components/rangeInput/rangeInput.component.tsx, module-new/src/components/rangeInput/rangeInput.stories.tsx, module-new/src/components/rangeInput/rangeInput.theme.css, module-new/src/index.ts
- Added radix range input
ARM-303
=> feat: ARM-303 added radix range input

module-new/src/components/checkbox/checkbox.stories.tsx, module-new/src/components/input/input.stories.tsx, module-new/src/components/select/select.component.tsx, module-new/src/components/select/select.stories.tsx, module-new/src/components/select/select.theme.css, module-new/src/components/select/select.utils.ts, module-new/src/index.ts, module-new/src/types/options.ts
- Added a multi select input that binds to an array
- Also fixed a casing issue on `data-testId` that was causing errors in the console.
- 'allowCreate' functionality supported
ARM-293
=> feat: ARM-293 - Added multi-select input

module-new/src/components/rating/index.ts, module-new/src/components/rating/rating.component.tsx, module-new/src/components/rating/rating.stories.tsx, module-new/src/components/rating/rating.theme.css, module-new/src/components/rating/rating.utils.spec.ts, module-new/src/components/rating/rating.utils.ts, module-new/src/components/spinner/spinner.component.tsx, module-new/src/components/spinner/spinner.stories.tsx, module-new/src/components/textArea/textArea.stories.tsx, module-new/src/components/validationErrors/validationErrors.component.tsx, module-new/src/index.ts, module/src/components/textArea/textArea.stories.tsx
- Added a rating input (used primarily for star rating based review systems.)
ARM-XX
=> feat: ARM-304 - Added a rating input for star ratings

README.md, module/package.json
- Added missing css export to package file
=> fix: - Added missing css export to package file

module/src/index.ts
=> fix: - Added missing toast export

module/CHANGELOG.md, module/src/components/button/button.theme.css, module/src/components/checkbox/checkbox.theme.css, module/src/components/dialog/dialog.theme.css, module/src/components/input/input.theme.css, module/src/components/radioGroup/radioGroup.theme.css, module/src/components/rangeInput/rangeInput.theme.css, module/src/components/select/select.theme.css, module/src/components/switch/switch.theme.css, module/src/components/textArea/textArea.theme.css, module/src/theme/variables.css
- Switched focus outline to box shadow for Safari bug
=> fix: - Switched focus outline to box shadow for Safari bug

module/src/index.ts
=> fix: - Added util exports

module/src/components/config/config.context.tsx, module/src/components/dialog/dialog.component.tsx, module/src/components/toast/toast.context.tsx
- Fixed some bad stuff
- (NextJS build errors because document is not defined)
=> add conditional check to make sure body exists

module/src/index.ts
- Added types export to barrel file
=> fix: - Added types export to barrel file

module/src/components/button/button.theme.css
- Added cursor:pointer to button input, making it more consistent with other inputs in Armstrong
=> fix: add cursor pointer to button element

module/src/index.ts
- Added missing validation component export
=> fix: - Added missing validation component export

module/CHANGELOG.md, module/src/components/checkbox/checkbox.component.tsx, module/src/components/checkboxList/checkboxList.component.tsx, module/src/components/codeInput/codeInput.component.tsx, module/src/components/config/config.context.tsx, module/src/components/dateTimeInput/dateTimeInput.component.tsx, module/src/components/dialog/dialog.component.tsx, module/src/components/input/input.component.tsx, module/src/components/radioGroup/radioGroup.component.tsx, module/src/components/rangeInput/rangeInput.component.tsx, module/src/components/rating/rating.component.tsx, module/src/components/select/select.component.tsx, module/src/components/select/select.stories.tsx, module/src/components/switch/switch.component.tsx, module/src/components/textArea/textArea.component.tsx, module/src/components/toast/toast.context.tsx, module/src/form/types.ts
- Added auto validate + touched state support.
- Fixed order of override between binding state and globals.
- Fixed some formatting issues.
=> feat: Added auto validate + touched state support

module/CHANGELOG.md, module/src/form/types.ts
- Minor type fix in Zod schema
=> fix: - Minor type fix in Zod schema

module/CHANGELOG.md, module/src/components/dialog/dialog.component.tsx
- Added missing close delay prop for styling dialogs
=> fix: - Added missing close delay prop for styling dialogs

module/CHANGELOG.md, module/src/components/dialog/dialog.component.tsx, module/src/components/select/select.component.tsx
- Correct wrong validation errors being sent to native select
=> fix: - Correct wrong validation errors being sent to native select

module/CHANGELOG.md, module/src/components/input/input.component.tsx
- Added "hidden" to the supported types on input
=> fix: - Added "hidden" to the supported types on input

module/src/components/switch/index.ts, module/src/index.ts, package-lock.json
- added missing index.ts for switch
- added it to the exported components
=> fix: exported switch as it wasn't getting exporterd

module/CHANGELOG.md, module/src/components/select/select.component.tsx, module/src/components/select/select.theme.css
- Fixed issue in which native select was not opening on arrow click
=> fix: - Fixed issue in which native select was not opening on arrow click

module/CHANGELOG.md, module/src/components/select/select.theme.css
Fixed issue with native select and box sizing
=> fix: - Fixed issue with native select and box sizing

module/CHANGELOG.md, module/src/components/select/select.component.tsx
- onInputChange now supported in select components
=> fix: - onInputChange now supported in select components

module/CHANGELOG.md, module/src/form/types.ts
Extended zod validation schema to allow refine
=> fix: ARM-- Extended zod validation schema to allow refine

module/CHANGELOG.md, module/src/form/hooks/useFormBase.ts, module/src/form/types.ts
- Adds a clear method because formProp can't receive undefined
=> fix: - Adds a clear method because formProp can't receive undefined

README.md, module/.storybook/manager.ts, module/CHANGELOG.md
fixed broken logo link in documentation
=> fix: fixed broken logo link in documentation

module/CHANGELOG.md, module/src/form/hooks/useBindingState.spec.ts, module/src/form/hooks/useBindingState.ts, module/src/form/hooks/useForm.ts, module/src/form/hooks/useFormBase.ts, module/src/form/types.ts, module/src/form/utils/validation.ts
Extended validation to allow root zod object + validate all + dynamic schema
=> feat: validation extensions

module/CHANGELOG.md, module/src/form/hooks/useForm.ts, module/src/form/types.ts, module/src/form/utils/validation.spec.ts, module/src/form/utils/validation.ts
fix: fixed issue with validation types
=> fix: fixed issue with validation types

module/src/components/select/select.component.tsx
- Added some cool stuff
- Fixed some bad stuff
ARM-XX
=> fix: fix docs on select

module/CHANGELOG.md, module/src/form/hooks/useForm.ts, module/src/form/types.ts
optional logging added for schema validation
=> fix: optional logging added for schema validation

module/CHANGELOG.md, module/src/form/types.ts
Added types to support zod union
=> fix: - Added types to support zod union

module/CHANGELOG.md, module/src/form/types.ts
- ZOD types now supporting enums
=> fix: - ZOD types now supporting enums

module/CHANGELOG.md, module/src/components/input/input.component.tsx
- Fixed number input to allow all valid numbers to be entered
ARM-221
=> fix: ARM-#221 - Fixed number input to allow all valid numbers to be entered

module/CHANGELOG.md, module/src/components/select/select.component.tsx
fixed issue in which client side filter can not be overridden
=> fix: fixed issue in which client side filter can not be overridden

module/.storybook/preview.tsx, module/CHANGELOG.md, module/package-lock.json, module/package.json, module/src/components/dropdownMenu/dropdownMenu.component.tsx, module/src/components/dropdownMenu/dropdownMenu.stories.tsx, module/src/components/dropdownMenu/dropdownMenu.theme.css, module/src/components/dropdownMenu/index.ts, module/src/components/tooltip/tooltip.theme.css, module/src/index.ts, module/src/theme/animations.css
- Implemented a dropdown menu component.
- Abstracted animations shared by tooltip + dropdown menu to avoid repetition.
=> feat: implemented a dropdown menu component

module/CHANGELOG.md, module/src/components/config/config.context.tsx, module/src/components/provider/provider.component.tsx, module/src/components/toast/toast.context.tsx
- Added use client directives for SSR support on context
=> fix: - Added use client directives for SSR support on context

module/CHANGELOG.md, module/src/components/checkbox/checkbox.component.tsx, module/src/components/checkbox/checkbox.theme.css
- Fixed bug causing checkbox to appear disabled when disabled attribute is present regardless of value
=> fix: Checkbox appears disabled when attribute is present regardless of value

README.md, module/src/components/button/button.theme.css, module/src/components/characterLimit/characterLimit.theme.css, module/src/components/checkbox/checkbox.theme.css, module/src/components/codeInput/codeInput.theme.css, module/src/components/dateTimeInput/dateTimeInput.theme.css, module/src/components/dropdownMenu/dropdownMenu.theme.css, module/src/components/input/input.theme.css, module/src/components/inputWrapper/inputWrapper.theme.css, module/src/components/progressBar/progressBar.theme.css, module/src/components/radioGroup/radioGroup.theme.css, module/src/components/rangeInput/rangeInput.theme.css, module/src/components/rating/rating.theme.css, module/src/components/select/select.theme.css, module/src/components/switch/switch.theme.css, module/src/components/textArea/textArea.theme.css, module/src/components/toast/toast.theme.css
- css left and right -> inline start / end
- Switch transformX directions depending on dir attribute
=> fix: update css properties to support right to left

module/package-lock.json, module/src/components/textArea/textArea.component.tsx
- exported textarea props
ARM-XX
=> fix: export textarea props

module/src/components/dateTimeInput/index.ts
- Fixed date time input exports
=> fix: - Fixed date time input exports

module/CHANGELOG.md, module/src/components/dateTimeInput/dateTimeInput.component.tsx, module/src/components/input/input.component.tsx, module/src/components/rangeInput/rangeInput.component.tsx, module/src/components/select/select.component.tsx, module/src/components/switch/switch.theme.css, module/src/components/textArea/textArea.component.tsx, module/src/components/toast/toast.theme.css, module/src/workarounds/radixDialog.ts
Fixes an annoying bug in the Radix dialog component. The bug meant that the user was unable to tab through inputs within a dialog without the dialog container stealing focus.
=> fix: - Temporary fix for annoying radix dialog focus bug

module/CHANGELOG.md, module/src/components/select/select.component.tsx, module/src/types/options.ts
- Fixes overflow bugs with react select inside radix modal
=> fix: - Fixes overflow bugs with react select inside radix modal

module/CHANGELOG.md, module/src/components/select/select.component.tsx
- Ability to set no options message on select
=> fix: - Ability to set no options message on select

module/CHANGELOG.md, module/src/components/button/button.component.tsx, module/src/components/button/button.theme.css, module/src/docs/variables.mdx, module/src/theme/variables.css, module/src/types/core.ts
- Added missing styling vars for outline button
=> fix: - Added missing styling vars for outline button

module/CHANGELOG.md, module/src/components/checkboxList/checkboxList.component.tsx, module/src/components/dropdownMenu/dropdownMenu.theme.css, module/src/components/radioGroup/radioGroup.component.tsx, module/src/components/radioGroup/radioGroup.theme.css, module/src/components/switch/switch.theme.css, module/src/components/textArea/textArea.theme.css
- Disabled states correct to read boolean value rather than style on presence.
- Validation blocks on checkbox/radio lists now only rendering if there are errors in the array.
=> fix: - disabled states + validation errors

module/src/components/dropdownMenu/dropdownMenu.theme.css
- Fixed bug preventing items in dropdown menu from highlighting
=> fix: - Fixed bug preventing items in dropdown menu from highlighting

module/CHANGELOG.md, module/src/components/dropdownMenu/dropdownMenu.component.tsx, module/src/components/dropdownMenu/dropdownMenu.stories.tsx
- Now passing event through to dropdown item click
=> fix: - Now passing event through to dropdown item click

module/CHANGELOG.md, module/src/components/dropdownMenu/dropdownMenu.component.tsx, module/src/components/dropdownMenu/dropdownMenu.stories.tsx
- Added optional header/footer to dropdown menu
=> feat: - Added optional header/footer to dropdown menu

module/CHANGELOG.md, module/src/components/select/select.component.tsx
- Fixed bug causing placeholder not to work on create select inputs
=> fix: - Fixed bug causing placeholder not to work on create select inputs

module/CHANGELOG.md, module/src/components/dropdownMenu/dropdownMenu.component.tsx
- Disabled prop now supported on dropdown menu
=> fix: - Disabled prop now supported on dropdown menu

module/CHANGELOG.md, module/src/components/dialog/dialog.component.tsx, module/src/components/dialog/dialog.stories.tsx
onBeforeUnload implemented on dialog to allow close to be prevented
=> feat: - onBeforeUnload implemented on dialog to allow close to be prevented

module/CHANGELOG.md, module/src/components/dropdownMenu/dropdownMenu.component.tsx, module/src/components/select/select.theme.css
- Fixes bug causing no screen interaction after launching dialog from dropdown menu
- Some prettier fixes
=> fix: - Dialog launch from dropdown menu bug fix

module/CHANGELOG.md, module/src/components/codeInput/codeInput.component.tsx
- Fixed bug causing right overlay on code input not to render
=> fix: - Fixed bug causing right overlay on code input not to render

module/package-lock.json, module/src/components/button/button.mdx, module/src/components/button/button.stories.tsx, module/src/components/characterLimit/characterLimit.mdx, module/src/components/checkbox/checkbox.mdx, module/src/components/checkbox/checkbox.stories.tsx, module/src/components/checkboxList/checkboxList.mdx, module/src/components/codeInput/codeInput.mdx, module/src/components/dateTimeInput/dateTimeInput.mdx, module/src/components/dateTimeInput/dateTimeInput.stories.tsx, module/src/components/dropdownMenu/dropdownMenu.mdx, module/src/components/dropdownMenu/dropdownMenu.stories.tsx, module/src/components/expandable/expandable.mdx, module/src/components/input/input.mdx, module/src/components/progressBar/progressBar.mdx, module/src/components/radioGroup/radioGroup.mdx, module/src/components/rangeInput/rangeInput.mdx, module/src/components/rating/rating.mdx, module/src/components/select/select.mdx, module/src/components/spinner/spinner.mdx, module/src/components/switch/switch.mdx, module/src/components/textArea/textArea.mdx, module/src/components/validationErrors/validationErrors.mdx, package-lock.json, storybook/.storybook/main.ts, storybook/package-lock.json
- Added .mdx documentation for each component in the `component` section
Component name
Short description
Preview (`default` story)
Corresponding code
List of props
Examples (the other stories & code examples)
=> feat: Update Armstrong documentation

module/CHANGELOG.md, module/src/form/types.ts
- Resolves issue with nested arrays in IValidationSchema
=> fix: - Resolves issue with nested arrays in IValidationSchema

module/src/form/utils/validation.spec.ts, module/src/form/utils/validation.ts
fix: - potential runtime fix for nested arrays in zod validation
=> fix: - potential runtime fix for nested arrays in zod validation

module/CHANGELOG.md, module/src/components/toast/toast.context.tsx, module/src/components/toast/toast.hooks.ts, module/src/components/toast/toast.mdx, module/src/components/toast/toast.stories.tsx
- Adds the ability to dismiss toasts programatically
=> feat: - Adds the ability to dismiss toasts programatically

module/src/components/dropdownMenu/dropdownMenu.mdx, module/src/components/dropdownMenu/dropdownMenu.stories.tsx
Corrects the story name and adds documentation for non-modal dropdown
=> fix: fixes the docs for non-modal dropdown

module/src/components/input/input.component.tsx
=> fix: bind attribute to correct prop

module/src/components/textArea/textArea.component.tsx
=> fix: add value prop to text area
