Rocketmakers/armstrong-edge

module/src/components/modal/index.ts

- Added `export * from './modal.hooks';` to the modal component
N/A

fix: added the modal hooks to the export

---

module/src/components/modal/modal.component.tsx

Fixed https://github.com/Rocketmakers/armstrong-edge/issues/45 by changing the modal wrapper `onClick` event to a `onMouseDown` so it doesn't incorrectly pick up mouse up events caused by dragging selections from within the dialog

fix: fixed dialogs closing when dragging from inside to outside

---

module/src/components/autoCompleteInput/autoCompleteInput.component.tsx
module/src/components/calendarInput/calendarInput.component.tsx
module/src/hooks/useIsFocused.ts

- Fixed a bug in the calendar input preventing January from being selected.
- Fixed a bug in the calendar input meaning client side validation was being cleared every render.
- Fixed a bug in autocomplete input preventing native focus and blur event support
N/A
- [✅] are your changes in Storybook?
- [✅] are any breaking changes documented in `docs/migrating_from_oldstrong.md`?
- [✅] does _everything_ have jsdoc?
- [✅] is everything exported from index.ts?
- [✅] are all new hooks added to `src/hooks/hooks.stories.mdx` or given their own docs in Storybook?
- [✅] are all new SCSS mixins added to `src/theme/mixins.stories.mdx`?
- [✅] are all new SCSS variables added to `src/theme/variables.stories.mdx`?

feat: calendar input bug fixes

---

module/package.json

Added an `scss` sideeffect so styling isn't excluded from storybook

fix: add scss sideffects so storybook styling works again

---

module/src/components/dropdown/dropdown.component.tsx
module/src/components/modal/modal.basic.scss
module/src/components/modal/modal.component.tsx
module/src/components/modal/modal.prototyping.scss
module/src/components/modal/modal.stories.tsx
module/src/components/sideMenu/sideMenu.component.tsx
module/src/components/tooltip/tooltip.component.tsx

- move centring of modals to basic theme from prototyping theme
- add new centred prop to modals to add above style, on by default
ARM-XX

feature/move-modal-centring-to-prototyping (I meant to basic, i named the branch wrong)

---

module/src/components/autoCompleteInput/autoCompleteInput.component.tsx
module/src/components/autoCompleteInputMulti/autoCompleteInputMulti.component.tsx
module/src/components/calendarInput/calendarInput.component.tsx
module/src/components/characterLimit/characterLimit.component.tsx
module/src/components/checkboxInput/checkboxInput.component.tsx
module/src/components/checkboxInputList/checkboxInputList.component.tsx
module/src/components/codeInput/codeInput.component.tsx
module/src/components/confirmPasswordInput/confirmPasswordInput.component.tsx
module/src/components/dateTimeInput/dateTimeInput.component.tsx
module/src/components/input/input.component.tsx
module/src/components/listBox/listBox.component.tsx
module/src/components/listBoxMulti/listBoxMulti.component.tsx
module/src/components/radioInputList/radioInputList.component.tsx
module/src/components/rangeInput/rangeInput.component.tsx
module/src/components/select/select.component.tsx
module/src/components/switchInput/switchInput.component.tsx
module/src/components/tabSelect/tabSelect.component.tsx
module/src/components/tagInput/tagInput.component.tsx
module/src/components/textArea/textArea.component.tsx
module/src/components/timeInput/timeInput.component.tsx
module/src/hooks/form/form.hooks.ts
module/src/hooks/form/formCustomInput.stories.mdx

- Renamed useBindingTools to useBindingState
- Still allow useBindingTools, but with clear deprecation notice and JSDoc
ARM-XX

feature/deprecate-useBindingTools (rename to useBindingState)

---

module/src/components/calendarInput/calendarInput.component.tsx
module/src/components/dateTimeInput/dateTimeInput.component.tsx
module/src/components/dateTimeInput/dateTimeInput.stories.tsx
module/src/hooks/calendar/calendar.types.ts
module/src/utils/dates.ts
module/src/utils/javascript.stories.mdx
module/src/utils/javascript.ts

- Calendar input bug fixed, was causing dates of type number to be returned as type string.
ISSUES CLOSED: https://github.com/Rocketmakers/armstrong-edge/issues/58

fix: Issue #58 - Calendar input bug fixed.

---

module/src/components/index.ts
module/src/components/sideMenu/index.ts

- Side menu component now being exported

fix: side menu component now being exported

---

module/src/hooks/hooks.stories.mdx

- Corrected useMatchMedia hook example to use the right format as the current example doesn't work
- [ x ] are your changes in Storybook?

Corrects matchmedia example on storybook

---

module/.storybook/preview.tsx
module/src/components/dialog/dialog.hooks.tsx
module/src/components/dialog/dialog.stories.tsx

- Allows content for a confirmation dialog to be passed in as an argument. Argument content will override hook level content on a per property basis.
- Added a story for confirmation dialog.
- Fixed a little build error in the handle close dialog story.

Confirmation dialog content override

---

module/src/hooks/useMatchMedia.ts

- Added a try catch block on event listener to fallback on older module
- Added another catch to better document any other errors that come from this hook

fix: add fallback to deprecated addListener

---

module/src/components/rangeInput/rangeInput.basic.scss
module/src/theme/mixins.scss
module/src/theme/mixins.stories.mdx

- Range input's thumb, on safari 16, do not move along track when being dragged. When webkit-appearance none 
https://www.loom.com/share/7b2b1853ea59476b89a4e7fb5c5a989c
https://www.loom.com/share/cf719ab1919941ffa34d341f4799e145
ARM-XX

fix: range input thumb moves along track on safari 16

---

module/src/components/numberInput/numberInput.component.tsx

- Added generic bindings to number input to support strict mode

fix: - Added generic bindings to number input to support strict mode

---

module-new/package-lock.json
module-new/package.json
module-new/src/components/config/config.context.tsx
module-new/src/components/dialog/dialog.component.tsx
module-new/src/components/provider/index.ts
module-new/src/components/provider/provider.component.tsx
module-new/src/components/toast/index.ts
module-new/src/components/toast/toast.component.tsx
module-new/src/components/toast/toast.context.tsx
module-new/src/components/toast/toast.hooks.ts
module-new/src/components/toast/toast.stories.mdx
module-new/src/components/toast/toast.stories.tsx
module-new/src/components/toast/toast.theme.css

- Added new Radix toast to module-new
- Created the unified <ArmstrongProvider> to handle toast and global config
ARM-318

feat: ARM-318 - Added new Radix toast to module-new

---

module-new/src/components/inputWrapper/inputWrapper.stories.mdx
module-new/src/components/inputWrapper/inputWrapper.stories.tsx
module-new/src/components/spinner/spinner.component.tsx
module-new/src/components/spinner/spinner.stories.tsx
module-new/src/components/validationErrors/validationErrors.stories.mdx
module-new/src/components/validationErrors/validationErrors.stories.tsx

- Add storybook components for InputWrapper and ValidationErrors
- Add storybook tests for InputWrapper, ValidationErrors and Spinner components
ARM-307
ARM-291
ARM-320

InputWrapper, ValidationErrors and Spinner storybook tests

---

module/.storybook/manager.ts
module/CHANGELOG.md
module/src/components/select/select.component.tsx
module/src/components/select/select.stories.tsx

- Fixed bug causing select placeholder not to work
- Type discrimination on select was complex and broken, now exporting `Select`, `MultiSelect` and `NativeSelect` as separate components.

Fix: Select placeholder and types

---

module/CHANGELOG.md
module/src/components/dateTimeInput/dateTimeInput.component.tsx

- Required prop now working on date inputs
- Calendar header buttons now have the correct type
- Left overlay in calendar input is now removable by sending `false`

fix: - Fixed issues with date input

---

module/CHANGELOG.md
module/src/components/select/select.component.tsx

Adds data attribute to native select so styleable when empty

fix: adds data attribute to native select so styleable when empty

---

module/src/components/select/select.component.tsx

changes the default of the search function from case sensitive to not and adds in a prop to make it so that you can select if it is or not.
- Added some cool stuff
- Fixed some bad stuff
ARM-XX

Changes the default of the search function on the Select component

---

module/CHANGELOG.md
module/src/form/hooks/useBindingState.spec.ts
module/src/form/hooks/useChildForm.spec.ts
module/src/form/hooks/useChildForm.ts
module/src/form/hooks/useFormBase.ts
module/src/form/hooks/useMyValidationErrorMessages.spec.ts
module/src/form/types.ts

bind now returns the full keychain back to the root, not just to the root of the child binder

feat: full key chain

---

module/.storybook/preview.tsx
module/CHANGELOG.md
module/src/components/dialog/dialog.theme.css
module/src/components/dropdownMenu/dropdownMenu.theme.css
module/src/components/expandable/expandable.theme.css
module/src/components/progressBar/progressBar.theme.css
module/src/components/rangeInput/rangeInput.theme.css
module/src/components/rating/rating.stories.tsx
module/src/components/rating/rating.theme.css
module/src/components/switch/switch.theme.css
module/src/components/toast/toast.theme.css
module/src/components/tooltip/tooltip.theme.css
module/src/docs/intro.stories.mdx
module/src/docs/variables.stories.mdx
module/src/theme/animations.css
module/src/theme/variables.css

- Added "Getting started" guide to Storybook docs.
- Added list of variables to Storybook docs.
- Centralised all CSS variable declarations to root level for consistency.
- Moved all animations to animations.css file for consistency.
- Renamed animations to correct casing (technically a breaking change, but I highly doubt any code outside of Armstrong is using these animations, it's not worth a v4.)
- Fixed issue in rating input stories causing some examples not to work.
- Fixed order of story groups to more logical order.

feat: added intro docs and centralised variables + animations

---

module/CHANGELOG.md
module/src/form/hooks/useFormBase.ts
module/src/hooks/useDidUpdateEffect.ts

- Fixes bug in which `isValid` on `useForm` was inaccurate when inputs are untouched or silent.
- Added React strict mode support to `useDidUpdateEffect` by resetting initial render tracker on unmount.

fix: - fixes bug with isValid on useForm + strict mode support

---

module/CHANGELOG.md
module/src/components/config/config.context.tsx
module/src/components/toast/toast.component.tsx
module/src/components/toast/toast.context.tsx
module/src/components/toast/toast.mdx
module/src/components/toast/toast.stories.tsx
module/src/types/core.ts

- Added `ignorePredicate` to allow custom logic for ignoring duplicate toasts
- Added `displayMode` option to control whether toasts are stacked or replaced
- Updated ToastProvider to respect new configuration via ArmstrongProvider
- Added Storybook stories to demonstrate and test both new props
- Wrote Playwright tests for `ignorePredicate` and `displayMode`
- Expanded Storybook documentation to cover all `ToastProvider` props

feat: - Added additional config options to avoid toast duplication

---

module/src/components/dropdownMenu/dropdownMenu.component.tsx
module/src/components/dropdownMenu/dropdownMenu.stories.tsx

Allowed passing radix's modal prop to the dropdown.
This allows the user to click on another dropdown menu without having to first click to close an open dropdown menu

feat: allowed passing radix's modal prop to the dropdown

---

module/src/form/utils/keyChain.spec.ts
module/src/form/utils/keyChain.ts

- Fixed a bug causing the first form item in an array to show an error message if any other form items had an error.

fix: fixed keychain string creation for keychains with zeros
